services:
  # Web Service (FastAPI Backend)
  - type: web
    name: english-cafe-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      alembic upgrade head
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DATABASE_URL
        fromDatabase:
          name: english-cafe-db
          property: connectionString
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: CORS_ORIGINS
        value: https://english-cafe.vercel.app,https://english-cafe.com
      - key: SECRET_KEY
        generateValue: true
      - key: SMTP_SERVER
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
    autoDeploy: true
    rootDir: backend

  # PostgreSQL Database
databases:
  - name: english-cafe-db
    databaseName: english_cafe
    user: english_cafe_user
    region: oregon
    plan: free
    postgresMajorVersion: 15